# Generated by Django 5.2.5 on 2025-08-30 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="certification",
            name="badge",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="certification",
            name="type",
            field=models.CharField(
                choices=[("aws", "AWS"), ("alx", "ALX"), ("other", "Other")],
                default="other",
                max_length=20,
            ),
        ),
    ]
