# Generated by Django 5.2.5 on 2026-09-17 21:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('recipient', models.CharField(blank=True, default='Hiring Manager', max_length=255)),
                ('job_description', models.TextField(blank=True, default='')),
                ('tone', models.CharField(default='executive', max_length=50)),
                ('include_photo', models.BooleanField(default=False)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cover_letters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255)),
                ('role', models.CharField(default='Network / Software Engineer', max_length=255)),
                ('status', models.CharField(choices=[('Applied', 'Applied'), ('Not yet Applied', 'Not yet Applied'), ('Interviewing', 'Interviewing'), ('Offer', 'Offer'), ('Rejected', 'Rejected')], default='Applied', max_length=50)),
                ('link', models.URLField(blank=True, default='', max_length=1000)),
                ('done', models.BooleanField(default=False)),
                ('google_search_link', models.CharField(blank=True, default='', max_length=1000)),
                ('job_requirements', models.TextField(blank=True, default='')),
                ('date_applied', models.DateField(blank=True, null=True)),
                ('take_by', models.CharField(blank=True, default='', max_length=255)),
                ('oa', models.BooleanField(default=False, verbose_name='Online Assessment')),
                ('phone_screen', models.BooleanField(default=False, verbose_name='Phone Screen')),
                ('interview', models.BooleanField(default=False, verbose_name='Interview')),
                ('interview_done', models.BooleanField(default=False, verbose_name='Interview Done')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_applied', '-created_at'],
            },
        ),
    ]
