# Generated by Django 5.2.5 on 2026-09-25 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='advert_ref',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Advert Ref / Grade'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='closing_date',
            field=models.DateField(blank=True, null=True, verbose_name='Closing Date'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='key_responsibilities',
            field=models.TextField(blank=True, default='', verbose_name='Key Responsibilities'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='shortlisted',
            field=models.BooleanField(default=False, verbose_name='Shortlisted?'),
        ),
    ]
