# Generated by Django 5.2.5 on 2026-08-07 06:16

import projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=projects.models.project_image_upload_path),
        ),
    ]
