# Generated by Django 5.2.5 on 2026-09-26 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='github_link',
            field=models.URLField(blank=True, help_text='GitHub repository, Packet Tracer .pkt file, or Lab config link', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='completion',
            field=models.CharField(default='100%', max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='link',
            field=models.URLField(blank=True, help_text='Live URL, Demo link, or Hosted architecture viewer', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(default='Active', max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='technologies',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(default='Web App', max_length=100),
        ),
    ]
