# Generated by Django 5.2.5 on 2026-09-18 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-published_at', '-created_at']},
        ),
        migrations.AddField(
            model_name='blogpost',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='Link to original article (e.g. on Medium)', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='cover_image',
            field=models.URLField(blank=True, default='', help_text='Header / preview image URL', max_length=1000),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='medium_guid',
            field=models.CharField(blank=True, help_text='Medium RSS GUID for deduplication', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='read_time_minutes',
            field=models.PositiveIntegerField(default=3, help_text='Estimated read time in minutes'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('medium', 'Medium')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='subtitle',
            field=models.TextField(blank=True, default='', help_text='Short description / excerpt'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='List of tags/categories'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=models.TextField(help_text='Full article content in Markdown or HTML'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
