# Generated by Django 5.2.5 on 2026-08-05 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='credential_url',
            field=models.URLField(blank=True, help_text='URL to verify the credential online', null=True),
        ),
        migrations.AddField(
            model_name='certification',
            name='in_progress',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='certification',
            name='badge',
            field=models.URLField(blank=True, help_text='URL to badge image (e.g. Credly badge image)', null=True),
        ),
        migrations.AlterField(
            model_name='certification',
            name='type',
            field=models.CharField(choices=[('aws', 'AWS'), ('alx', 'ALX'), ('oracle', 'Oracle'), ('badge', 'Badge'), ('other', 'Other')], max_length=10),
        ),
    ]
