# Generated by Django 5.2.5 on 2026-09-18 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reference',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='reference',
            name='is_approved',
            field=models.BooleanField(default=True, help_text='Whether this reference is approved to be publicly displayed'),
        ),
    ]
